name: Docker Image CI

on:
  push:
    branches: [ buster ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        echo "$DOCKER_PASSWORD" | docker login --username ${{ github.actor }} --password-stdin
        docker build . --file Dockerfile --tag ${{ github.actor }}/wireguard:latest --tag ${{ github.actor }}/wireguard:buster
        docker push ${{ github.actor }}/wireguard
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
